# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - creditscoremodel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://creditscoremodel.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_38ba85817f8a4b909670d8c704cd3d0b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_25653e0e85e34ebbbf130433633197f5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: creditscoremodel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_38ba85817f8a4b909670d8c704cd3d0b }}/creditscoremodel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'creditscoremodel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4697d3c2a77e46b7aed3691136a6a0b0 }}
        images: 'creditscoremodel.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_38ba85817f8a4b909670d8c704cd3d0b }}/creditscoremodel:${{ github.sha }}'